allowBuilds:
  "@parcel/watcher": false
  core-js: false
  esbuild: true
  vue-demi: false
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.5'
  - vue-tsc@3.3.5
  - happy-dom@20.10.6
  - browserslist@4.28.6
  - '@bhsd/browser@1.1.0'
  - '@bhsd/cm-util@2.3.0'
  - '@bhsd/codemirror-mediawiki@4.2.0'
  - '@bhsd/lezer-abusefilter@0.5.0'
  - postcss@8.5.17
  - svgo@4.0.2
  - stylelint-config-wikimedia@0.19.3
overrides:
  "@types/oojs-ui": "latest"
  "browserslist-config-wikimedia": "latest"
  "emoji-regex": "latest"
  "known-css-properties": "latest"
  "dompurify": ">=3.4.11"
patchedDependencies:
  alpha-sort: patches/alpha-sort.patch
  esbuild-css-modules-plugin: patches/esbuild-css-modules-plugin.patch
  types-mediawiki-api: patches/types-mediawiki-api.patch
publicHoistPattern:
  - "*eslint-plugin*"
