import friendlytag from './modules/friendlytag.js';
import friendlytalkback from './modules/friendlytalkback.js';
import twinkle from './modules/twinkle.js';
import twinklearv from './modules/twinklearv.js';
import twinklebatchdelete from './modules/twinklebatchdelete.js';
import twinklebatchprotect from './modules/twinklebatchprotect.js';
import twinklebatchundelete from './modules/twinklebatchundelete.js';
import twinkleblock from './modules/twinkleblock.js';
import twinkleclose from './modules/twinkleclose.js';
import twinkleconfig from './modules/twinkleconfig.js';
import twinklecopyvio from './modules/twinklecopyvio.js';
import twinklediff from './modules/twinklediff.js';
import twinklefluff from './modules/twinklefluff.js';
import twinkleimage from './modules/twinkleimage.js';
import twinkleprotect from './modules/twinkleprotect.js';
import twinklespeedy from './modules/twinklespeedy.js';
import twinklestub from './modules/twinklestub.js';
import twinkleunlink from './modules/twinkleunlink.js';
import twinklewarn from './modules/twinklewarn.js';
import twinklexfd from './modules/twinklexfd.js';

$(twinkle);
$(twinkleconfig);
$(friendlytag);
$(friendlytalkback);
$(twinklearv);
$(twinklebatchdelete);
$(twinklebatchprotect);
$(twinklebatchundelete);
$(twinkleblock);
$(twinkleclose);
$(twinklecopyvio);
$(twinklediff);
$(twinklefluff);
$(twinkleimage);
$(twinkleprotect);
$(twinklespeedy);
$(twinklestub);
$(twinkleunlink);
$(twinklewarn);
$(twinklexfd);
